# .github/workflows/installer.yml
name: Build and Upload Commitify Installer

on:
  workflow_run:
    workflows: ["Build Executables"]   # Must match the 'name:' in main.yml
    types:
      - completed
  workflow_dispatch:

jobs:
  build-installer:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}   # Only run if main.yml succeeded
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download commitify.exe from release
        uses: robinraju/release-downloader@v1.8
        with:
          latest: true
          fileName: commitify.exe
          out-file-path: CommitifyInstaller

      - name: Compile Inno Setup Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: Commitify.iss

      - name: Upload installer to release
        uses: softprops/action-gh-release@v2
        with:
          files: CommitifyInstaller.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
